kind: DataPowerAssembly
apiVersion: api.ibm.com/v1
metadata:
  name: PetstoreDPAssembly
  namespace: PetstoreProject
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - datapower
spec:
  x-ibm-configuration:
    gateway: datapower-api-gateway
    assembly:
      execute: []
