kind: Plan
apiVersion: api.ibm.com/v1
metadata:
  name: PetstorePlan
  namespace: PetstoreProject
  version: '1.0'
  tags: []
  description: ''
spec:
  qos:
    withQuota:
      plan-limit:
        - $ref: PetstoreProject:Quota-kbw28a:1.0
  extensions:
    dp-gateway:
      spec:
        approvalRequired: true
        withRateLimit:
          - name: rate-limit-1
            maxRequest: 1000
            interval: 60h
        withAssemblyCountLimit:
          - name: assembly-cl-1
            maxRequest: 100
            hard-limit: true
            cache-only: true
            is-client: true
            use-api-name: false
            use-app-id: false
            use-client-id: false
            dynamic-value: 10
            auto-decrement: true
        withAssemblyRateLimit:
          - name: assembly-rl-1
            maxRequest: 10
            interval: 2s
            cache-only: true
            is-client: true
            use-api-name: false
            use-app-id: false
            use-client-id: false
            dynamic-value: 10
