kind: Product
apiVersion: api.ibm.com/v1
metadata:
  name: PetstoreProduct
  namespace: PetstoreProject
  version: '1.0'
  tags: []
  description: ''
spec:
  apis:
    - $ref: PetstoreProject:PetstoreAPI:1.0
  plans:
    - $ref: PetstoreProject:PetstorePlan:1.0
