kind: Quota
apiVersion: api.ibm.com/v1
metadata:
  name: Quota-kbw28a
  namespace: PetstoreProject
  version: '1.0'
  tags: []
  description: ''
spec:
  maxRequest: 1000
  interval: 60h
  extensions:
    dp-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        onLimitReach: block
