kind: StagedPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: Petstore-Sequence
  version: '1.0'
  namespace: webMethodsPetStore
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  routing:
    - $ref: webMethodsPetStore:Petstore-Invoke:1.0