kind: Invoke
apiVersion: api.ibm.com/v1
metadata:
  name: Petstore-Invoke
  namespace: webMethodsPetStore
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  endpoint:
    http:
      target:
        timeout: 30
        url: https://petstore3.swagger.io/api/v3
      verb: CUSTOM
