kind: StagedPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: SampleStagedPolSeq
  namespace: BasicInvokeProject
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  routing:
    - $ref: BasicInvokeProject:SampleInvoke:1.0
